# Site settings
title: Data-story on friendships mobility
description: Website on our analysis of Foursquare datasets to predict the evolution of friendships in the future
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Who will gain friendships?
user_description: Datomic Dataster
user_title: An deep analysis of Foursquare friendships dynamics

# Markdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

exclude: ['package.json', 'src' , 'node_modules']
